Adding Dockerfile, Mayhemfile and mayhem.yml
mayhemheroes/apollo-rs pull request #1
Opened 2022-04-26 01:59 UTC by prateekvishnu

2022-04-27 01:06 UTC, xansec requested changes

2022-04-27 01:06 UTC, xansec commented on Mayhemfile
> +image: ghcr.io/prateekvishnu/apollo-rs:latest
Please omit the image name in the Mayhemfile.

2022-04-27 01:06 UTC, xansec commented on Mayhemfile
> +target: apollo-rs
Your Mayhemfile has two targets. Please either remove one of the `cmd:` fields, or split this into multiple Mayhemfiles (and actions). The target name should also reflect the name of the target binary. So, for example, if your target command was `/lexer`, the target field here should show `lexer` (this helps disambiguate target runs if, for example, you do have multiple Mayhemfiles for the same project).

2022-04-27 01:45 UTC, prateekvishnu commented
Resolved changes.

2022-04-28 01:35 UTC, xansec approved these changes

2022-04-28 01:35 UTC, xansec commented
LGTM!

2022-04-28 01:35 UTC, merged